### ISSUE TITLE
Have trouble loading models

### ISSUE THREAD

**Issue by Dwrety** [holm-aune-bachelor2018/ctc#2]
I trained and saved a model successfully, but when I load back the model, it gave this error: 
I am working on Windows 10 with tensorflow r1.10.`[<tf.Tensor 'classifier/Reshape_1:0' shape=(?, ?, 47) dtype=float32>, <tf.Tensor 'labels:0' shape=(?, ?) dtype=float32>, <tf.Tensor 'input_length:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'label_length:0' shape=(?, 1) dtype=float32>]
XXX lineno: 358, opcode: 47
Traceback (most recent call last):
  File "D:\11785\HW3\hw3p2-data-V2\runner.py", line 332, in <module>
    train()
  File "D:\11785\HW3\hw3p2-data-V2\runner.py", line 299, in train
    net = tf.keras.models.load_model("models/model_every_ckpt_best", custom_objects=custom_objects)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 229, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 306, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1219, in from_config
    process_node(layer, node_data)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1179, in process_node
    layer(input_tensors, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\core.py", line 715, in call
    return self.function(inputs, **arguments)
  File "D:/11785/HW3/hw3p2-data-V2/modules.py", line 358, in ctc_lambda_func
    y_pred, labels, input_length, label_length = args
SystemError: unknown opcode
[Finished in 26.4s with exit code 1]`
Seems the Lambda layer is causing this problem, do you know why?

**Comment by tusharrakshe** [comment]
I also got the same problem. I think the dummy function for ctc loss calculation causing problem.

**Comment by anitakra** [comment]
I haven't encountered this problem, but I can see that you use a newer version of TensorFlow which might have brought some breaking changes. We aren't really maintaining this repository at the moment, so my best suggestion would be to try and use the versions listed in the project description.
